### ISSUE TITLE
联机时会发生错误导致无法正常联机

### ISSUE THREAD

**Issue by HanYuCR** [Dubhe-Studio/BugJump#15]
1.20.1 Fabric
联机报错Internal Exception: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2532 failed
![复现](https://github.com/Dubhe-Studio/BugJump/assets/126944908/cb86a49d-dd97-4fae-bc78-f826100f8bee)
[客户端latest.log](https://github.com/Dubhe-Studio/BugJump/files/12268747/latest.log)
[服务端latest.log](https://github.com/Dubhe-Studio/BugJump/files/12268748/latest.log)
![模组列表](https://github.com/Dubhe-Studio/BugJump/assets/126944908/8c0d4d2d-79f2-4ed8-84c7-c28f5d26f65c)
我本来想把这个模组放进我的整合包里，可是在我测试联机时发生这个报错，经过排查就是这个模组的问题，很遗憾。这是个不错的Mod，希望您能快速解决

**Comment by JiDW** [comment]
We have the same bug on 1.19.2 when trying to join a server running fabric latest version (0.11.2)

**Comment by meishiffx** [comment]
我使用1.20.1-1.2.0同样遇到了这个问题（

**Comment by SHUJIANGCHUNSHUI** [comment]
这个问题解决了吗？大家似乎都是一样的报错代码）
