### ISSUE TITLE
The kind of issue happened even with BugJump

### ISSUE THREAD

**Issue by ChromaPIE** [Dubhe-Studio/BugJump#9]
Don't know if it can be fixed by the mod but imma shoot the shot. Happens when the world finished loading and about to hop into it

Crash log: https://mclo.gs/tIOt46Y

**Comment by ChromaPIE** [comment]
Update: The version on Modrinth seems to be imcompatible with Better Biome Blend or the log simply decided to blame a random mod. Game crashes on booting up. No such problem with the one from MCMOD.

Log: https://mclo.gs/AiYtTdn

**Comment by Gu-ZT** [comment]
> Update: The version on Modrinth seems to be imcompatible with Better Biome Blend or the log simply decided to blame a random mod. Game crashes on booting up. No such problem with the one from MCMOD.
> 
> Log: https://mclo.gs/AiYtTdn

The files on Modrinth are the same as those on MCMOD, only the default state of the Feature has been modified

**Comment by Gu-ZT** [comment]
> Don't know if it can be fixed by the mod but imma shoot the shot. Happens when the world finished loading and about to hop into it
> 
> Crash log: https://mclo.gs/tIOt46Y

What is imma？

**Comment by ChromaPIE** [comment]
That's weird. **I'mma (=I am going to)** delete the config file and let the mod regenerate one and see how it's working.

By the way I'm getting the mod file named after BugJump-1.0.0-**1.18.2**, it'll still work for 1.19.2 or it's actually mistakenly uploaded?

And please, please make sure if the crash mentioned at the top of the thread can be solved by BugJump cuz this issue is not actually about where should I download the mod that causes no problem with the booting of the game.

Follow up: Nope. Still crashing.

**Comment by Gu-ZT** [comment]
> That's weird. **I'mma (=I am going to)** delete the config file and let the mod regenerate one and see how it's working.
> 
> By the way I'm getting the mod file named after BugJump-1.0.0-**1.18.2**, it'll still work for 1.19.2 or it's actually mistakenly uploaded?
> 
> And please, please make sure if the crash mentioned at the top of the thread can be solved by BugJump cuz this issue is not actually about where should I download the mod that causes no problem with the booting of the game.
> 
> Follow up: Nope. Still crashing.

The version on modrith has multiple files. You should click to enter the version details page and select the specific file to download
![image](https://user-images.githubusercontent.com/34372427/219959202-db086f41-b317-4200-8596-4c60841bbe11.png)

**Comment by ChromaPIE** [comment]
This will make mod managers like Ferium only be able to download the Primary one. I don't know how it works but you prolly need to separate them into two entries and specify the compatible minecraft version for each of them.

**Comment by ChromaPIE** [comment]
Nah don't close it bro the issue is not even about the modrinth or MCMOD stuff. would you scroll all the way up and check the crash report real quick? @Gu-ZT

**Comment by Gu-ZT** [comment]
> Nah don't close it bro the issue is not even about the modrinth or MCMOD stuff. would you scroll all the way up and check the crash report real quick? @Gu-ZT

You can try [this](https://github.com/Dubhe-Studio/BugJump/actions/runs/4283892887)

**Comment by ChromaPIE** [comment]
Seems to be working but im not sure. ill let you know if theres another crash.

**Comment by ChromaPIE** [comment]
@Gu-ZT no such problem since. plz consider releasing this version
